name1 = input("What is your name?\n").lower()
name2 = input("What is their name?\n").lower()
t=name1.count("t")+name2.count("t")
r=name1.count("r")+name2.count("r")
u=name1.count("u")+name2.count("u")
e=name1.count("e")+name2.count("e")
t1=str(t+r+u+e)

l=name1.count("l")+name2.count("l")
o=name1.count("o")+name2.count("o")
v=name1.count("v")+name2.count("v")
e=name1.count("e")+name2.count("e")
t2=str(l+o+v+e)
print(t1+t2)
